use crate::app_info::GET_APP_INFO_COMMAND;
use crate::conversations::{
    DELETE_CONVERSATION_COMMAND, GET_CONVERSATION_COMMAND, LIST_CONVERSATIONS_COMMAND,
};
use crate::credentials::{
    CREATE_CREDENTIAL_COMMAND, DELETE_CREDENTIAL_COMMAND, LIST_CREDENTIALS_COMMAND,
    REPLACE_CREDENTIAL_COMMAND,
};
use crate::model_runtime::{
    CANCEL_MODEL_OPERATION_COMMAND, CANCEL_MODEL_RUNTIME_OPERATION_COMMAND,
    CONFIGURE_MODEL_RUNTIME_COMMAND, GET_MODEL_RUNTIME_STATUS_COMMAND,
    GET_MODEL_SLOT_STATUS_COMMAND, LOAD_MODEL_COMMAND, PROBE_MODEL_RUNTIME_COMMAND,
    START_MODEL_RUNTIME_COMMAND, STOP_MODEL_RUNTIME_COMMAND, UNLOAD_MODEL_COMMAND,
};
use crate::providers::{CANCEL_CHAT_STREAM_COMMAND, START_CHAT_STREAM_COMMAND};
use crate::storage::{
    GET_APP_SETTINGS_COMMAND, RESET_APP_SETTINGS_COMMAND, UPDATE_APP_SETTINGS_COMMAND,
};

pub fn typescript_bindings() -> String {
    format!(
        r#"// Generated by lattice-core. Do not edit by hand.

export const APP_COMMANDS = {{
  getAppInfo: '{get_app_info_command}',
  getAppSettings: '{get_app_settings_command}',
  updateAppSettings: '{update_app_settings_command}',
  resetAppSettings: '{reset_app_settings_command}',
  getModelRuntimeStatus: '{get_model_runtime_status_command}',
  configureModelRuntime: '{configure_model_runtime_command}',
  probeModelRuntime: '{probe_model_runtime_command}',
  startModelRuntime: '{start_model_runtime_command}',
  stopModelRuntime: '{stop_model_runtime_command}',
  cancelModelRuntimeOperation: '{cancel_model_runtime_operation_command}',
  getModelSlotStatus: '{get_model_slot_status_command}',
  loadModel: '{load_model_command}',
  unloadModel: '{unload_model_command}',
  cancelModelOperation: '{cancel_model_operation_command}',
  startChatStream: '{start_chat_stream_command}',
  cancelChatStream: '{cancel_chat_stream_command}',
  listConversations: '{list_conversations_command}',
  getConversation: '{get_conversation_command}',
  deleteConversation: '{delete_conversation_command}',
  listCredentials: '{list_credentials_command}',
  createCredential: '{create_credential_command}',
  replaceCredential: '{replace_credential_command}',
  deleteCredential: '{delete_credential_command}'
}} as const;

export type AppCommand = (typeof APP_COMMANDS)[keyof typeof APP_COMMANDS];

export type NativeAppRuntime = 'tauri';

export type BuildProfile = 'debug' | 'release';

export type AppearancePreference = 'system' | 'light' | 'dark';

export type ModelRuntimeAvailability =
  'missing' | 'unsupported' | 'stopped' | 'running' | 'unreachable' | 'unknown';

export type RuntimeDaemonStatus = 'running' | 'notRunning' | 'unknown';

export type RuntimeServerStatus = 'running' | 'stopped' | 'unreachable' | 'unknown';

export type RuntimeOperationOutcome =
  | 'started'
  | 'alreadyRunning'
  | 'stopped'
  | 'alreadyStopped'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export type ModelOperationOutcome =
  | 'loaded'
  | 'alreadyLoaded'
  | 'unloaded'
  | 'alreadyUnloaded'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export interface NativeAppInfo {{
  readonly name: string;
  readonly version: string;
  readonly buildProfile: BuildProfile;
  readonly runtime: NativeAppRuntime;
  readonly target: string;
}}

export interface AppError {{
  readonly code: string;
  readonly message: string;
  readonly recoverable: boolean;
  readonly correlationId?: string;
}}

export interface AppSettings {{
  readonly schemaVersion: number;
  readonly revision: number;
  readonly appearance: AppearancePreference;
  readonly idleUnloadMinutes: number;
}}

export interface UpdateAppSettingsRequest {{
  readonly expectedRevision: number;
  readonly appearance?: AppearancePreference;
  readonly idleUnloadMinutes?: number;
}}

export interface ResetAppSettingsRequest {{
  readonly expectedRevision: number;
}}

export interface RuntimeProbeApproval {{
  readonly executableFingerprint: string;
  readonly cliVersion: string;
  readonly checkedAtUnixSeconds: number;
}}

export interface RuntimeDaemonObservation {{
  readonly status: RuntimeDaemonStatus;
  readonly pid?: number;
  readonly isDaemon?: boolean;
  readonly version?: string;
}}

export interface RuntimeServerObservation {{
  readonly status: RuntimeServerStatus;
  readonly port?: number;
  readonly endpoint?: string;
}}

export interface RuntimeOwnershipOwned {{
  readonly state: 'owned';
  readonly daemonPid: number;
  readonly executableFingerprint: string;
  readonly ownedSinceUnixSeconds: number;
}}

export interface RuntimeOwnershipAttached {{
  readonly state: 'attached';
}}

export interface RuntimeOwnershipUnknown {{
  readonly state: 'unknown';
}}

export type RuntimeOwnership =
  RuntimeOwnershipOwned | RuntimeOwnershipAttached | RuntimeOwnershipUnknown;

export interface ModelRuntimeStatus {{
  readonly revision: number;
  readonly executablePath?: string;
  readonly availability: ModelRuntimeAvailability;
  readonly cliVersion?: string;
  readonly approved?: RuntimeProbeApproval;
  readonly daemon: RuntimeDaemonObservation;
  readonly server: RuntimeServerObservation;
  readonly ownership: RuntimeOwnership;
  readonly lastOperation?: RuntimeOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}}

export interface ConfigureModelRuntimeRequest {{
  readonly expectedRevision: number;
  readonly executablePath: string;
}}

export interface ProbeModelRuntimeRequest {{
  readonly expectedRevision: number;
}}

export interface StartModelRuntimeRequest {{
  readonly expectedRevision: number;
}}

export interface StopModelRuntimeRequest {{
  readonly expectedRevision: number;
}}

export type CancelModelRuntimeOperationRequest = Record<string, never>;

export interface ModelDescriptor {{
  readonly modelKey: string;
  readonly displayName: string;
  readonly architecture?: string;
  readonly isLlm: boolean;
  readonly sizeBytes?: number;
}}

export interface LoadedModelObservation {{
  readonly identifier: string;
  readonly modelKey: string;
  readonly architecture?: string;
  readonly sizeBytes?: number;
}}

export interface ModelLoadOwnershipOwned {{
  readonly state: 'owned';
  readonly identifier: string;
  readonly modelKey: string;
  readonly loadedSinceUnixSeconds: number;
}}

export interface ModelLoadOwnershipAttached {{
  readonly state: 'attached';
  readonly identifier: string;
  readonly modelKey: string;
}}

export interface ModelLoadOwnershipUnknown {{
  readonly state: 'unknown';
}}

export type ModelLoadOwnership =
  ModelLoadOwnershipOwned | ModelLoadOwnershipAttached | ModelLoadOwnershipUnknown;

export interface ModelSlotStatus {{
  readonly revision: number;
  readonly installed: readonly ModelDescriptor[];
  readonly loaded?: LoadedModelObservation;
  readonly ownership: ModelLoadOwnership;
  readonly lastOperation?: ModelOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}}

export type GetModelSlotStatusRequest = Record<string, never>;

export interface LoadModelRequest {{
  readonly expectedRevision: number;
  readonly modelKey: string;
}}

export interface UnloadModelRequest {{
  readonly expectedRevision: number;
}}

export type CancelModelOperationRequest = Record<string, never>;

export type ChatRole = 'system' | 'user' | 'assistant';

export interface ChatMessage {{
  readonly role: ChatRole;
  readonly text: string;
}}

export interface ChatRequest {{
  readonly modelKey: string;
  readonly messages: readonly ChatMessage[];
}}

// Amended by 0.9 (conversation persistence): the command's actual request
// wraps the unchanged ChatRequest above with conversation identity.
export interface StartChatStreamRequest {{
  readonly conversationId: string | null;
  readonly chat: ChatRequest;
}}

export interface ChatRunHandle {{
  readonly runId: string;
  readonly conversationId: string;
}}

export interface CancelChatStreamRequest {{
  readonly runId: string;
}}

export type ChatFinishReason = 'stop' | 'maxOutputTokens';

export interface ChatStreamEventStarted {{
  readonly kind: 'started';
  readonly runId: string;
  readonly modelKey: string;
}}

export interface ChatStreamEventDelta {{
  readonly kind: 'delta';
  readonly runId: string;
  readonly sequence: number;
  readonly text: string;
}}

export interface ChatStreamEventCompleted {{
  readonly kind: 'completed';
  readonly runId: string;
  readonly sequence: number;
  readonly finishReason: ChatFinishReason;
}}

export interface ChatStreamEventCancelled {{
  readonly kind: 'cancelled';
  readonly runId: string;
  readonly sequence: number;
}}

export interface ChatStreamEventFailed {{
  readonly kind: 'failed';
  readonly runId: string;
  readonly sequence: number;
  readonly error: AppError;
}}

export type ChatStreamEvent =
  | ChatStreamEventStarted
  | ChatStreamEventDelta
  | ChatStreamEventCompleted
  | ChatStreamEventCancelled
  | ChatStreamEventFailed;

export type GenerationStatus = 'complete' | 'streaming' | 'cancelled' | 'failed' | 'interrupted';

export interface Message {{
  readonly id: string;
  readonly conversationId: string;
  readonly sequence: number;
  readonly role: ChatRole;
  readonly text: string;
  readonly status: GenerationStatus;
  readonly providerKey?: string;
  readonly modelKey?: string;
  readonly errorMessage?: string;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}}

export interface Conversation {{
  readonly id: string;
  readonly title: string;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}}

export interface ConversationSummary {{
  readonly id: string;
  readonly title: string;
  readonly updatedAtUnixSeconds: number;
  readonly messageCount: number;
  readonly lastStatus?: GenerationStatus;
}}

export interface ConversationCursor {{
  readonly updatedAtUnixSeconds: number;
  readonly id: string;
}}

export interface ListConversationsRequest {{
  readonly limit?: number;
  readonly before?: ConversationCursor;
}}

export interface ListConversationsResponse {{
  readonly conversations: readonly ConversationSummary[];
  readonly nextBefore?: ConversationCursor;
}}

export interface GetConversationRequest {{
  readonly conversationId: string;
  readonly limit?: number;
  readonly beforeSequence?: number;
}}

export interface ConversationDetail {{
  readonly conversation: Conversation;
  readonly messages: readonly Message[];
  readonly hasMoreBefore: boolean;
}}

export interface DeleteConversationRequest {{
  readonly conversationId: string;
}}

export type CredentialAvailability = 'available' | 'locked' | 'missing' | 'unsupported';

// No secret field, structurally — Angular never sees a resolved value, only
// this reference shape. See the credentials spec's "Lattice SHALL Acquire A
// New Or Replacement Secret Through Native Entry Only".
export interface CredentialRef {{
  readonly id: string;
  readonly label: string;
  readonly providerKey: string;
  readonly availability: CredentialAvailability;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}}

export interface CreateCredentialRequest {{
  readonly label: string;
  readonly providerKey: string;
}}

export interface ReplaceCredentialRequest {{
  readonly id: string;
}}

export interface DeleteCredentialRequest {{
  readonly id: string;
}}
"#,
        get_app_info_command = GET_APP_INFO_COMMAND,
        get_app_settings_command = GET_APP_SETTINGS_COMMAND,
        update_app_settings_command = UPDATE_APP_SETTINGS_COMMAND,
        reset_app_settings_command = RESET_APP_SETTINGS_COMMAND,
        get_model_runtime_status_command = GET_MODEL_RUNTIME_STATUS_COMMAND,
        configure_model_runtime_command = CONFIGURE_MODEL_RUNTIME_COMMAND,
        probe_model_runtime_command = PROBE_MODEL_RUNTIME_COMMAND,
        start_model_runtime_command = START_MODEL_RUNTIME_COMMAND,
        stop_model_runtime_command = STOP_MODEL_RUNTIME_COMMAND,
        cancel_model_runtime_operation_command = CANCEL_MODEL_RUNTIME_OPERATION_COMMAND,
        get_model_slot_status_command = GET_MODEL_SLOT_STATUS_COMMAND,
        load_model_command = LOAD_MODEL_COMMAND,
        unload_model_command = UNLOAD_MODEL_COMMAND,
        cancel_model_operation_command = CANCEL_MODEL_OPERATION_COMMAND,
        start_chat_stream_command = START_CHAT_STREAM_COMMAND,
        cancel_chat_stream_command = CANCEL_CHAT_STREAM_COMMAND,
        list_conversations_command = LIST_CONVERSATIONS_COMMAND,
        get_conversation_command = GET_CONVERSATION_COMMAND,
        delete_conversation_command = DELETE_CONVERSATION_COMMAND,
        list_credentials_command = LIST_CREDENTIALS_COMMAND,
        create_credential_command = CREATE_CREDENTIAL_COMMAND,
        replace_credential_command = REPLACE_CREDENTIAL_COMMAND,
        delete_credential_command = DELETE_CREDENTIAL_COMMAND
    )
}

#[cfg(test)]
mod tests {
    use super::typescript_bindings;
    use std::fs;
    use std::path::PathBuf;

    #[test]
    fn committed_typescript_bindings_match_rust_contract() -> Result<(), Box<dyn std::error::Error>>
    {
        let bindings_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/types/src/generated.ts");
        let committed_bindings = fs::read_to_string(bindings_path)?;

        assert_eq!(committed_bindings, typescript_bindings());
        Ok(())
    }
}
