use crate::app_info::GET_APP_INFO_COMMAND;
use crate::settings::{
    GET_APP_SETTINGS_COMMAND, RESET_APP_SETTINGS_COMMAND, UPDATE_APP_SETTINGS_COMMAND,
};

pub fn typescript_bindings() -> String {
    format!(
        r#"// Generated by lattice-core. Do not edit by hand.

export const APP_COMMANDS = {{
  getAppInfo: '{get_app_info_command}',
  getAppSettings: '{get_app_settings_command}',
  updateAppSettings: '{update_app_settings_command}',
  resetAppSettings: '{reset_app_settings_command}'
}} as const;

export type AppCommand = (typeof APP_COMMANDS)[keyof typeof APP_COMMANDS];

export type NativeAppRuntime = 'tauri';

export type BuildProfile = 'debug' | 'release';

export type AppearancePreference = 'system' | 'light' | 'dark';

export interface NativeAppInfo {{
  readonly name: string;
  readonly version: string;
  readonly buildProfile: BuildProfile;
  readonly runtime: NativeAppRuntime;
  readonly target: string;
}}

export interface AppError {{
  readonly code: string;
  readonly message: string;
  readonly recoverable: boolean;
  readonly correlationId?: string;
}}

export interface AppSettings {{
  readonly schemaVersion: number;
  readonly revision: number;
  readonly appearance: AppearancePreference;
  readonly idleUnloadMinutes: number;
}}

export interface UpdateAppSettingsRequest {{
  readonly expectedRevision: number;
  readonly appearance?: AppearancePreference;
  readonly idleUnloadMinutes?: number;
}}

export interface ResetAppSettingsRequest {{
  readonly expectedRevision: number;
}}
"#,
        get_app_info_command = GET_APP_INFO_COMMAND,
        get_app_settings_command = GET_APP_SETTINGS_COMMAND,
        update_app_settings_command = UPDATE_APP_SETTINGS_COMMAND,
        reset_app_settings_command = RESET_APP_SETTINGS_COMMAND
    )
}

#[cfg(test)]
mod tests {
    use super::typescript_bindings;
    use std::fs;
    use std::path::PathBuf;

    #[test]
    fn committed_typescript_bindings_match_rust_contract() -> Result<(), Box<dyn std::error::Error>>
    {
        let bindings_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/types/src/generated.ts");
        let committed_bindings = fs::read_to_string(bindings_path)?;

        assert_eq!(committed_bindings, typescript_bindings());
        Ok(())
    }
}
