// Generated by lattice-core. Do not edit by hand.

export const APP_COMMANDS = {
  getAppInfo: 'get_app_info',
  getAppSettings: 'get_app_settings',
  updateAppSettings: 'update_app_settings',
  resetAppSettings: 'reset_app_settings'
} as const;

export type AppCommand = (typeof APP_COMMANDS)[keyof typeof APP_COMMANDS];

export type NativeAppRuntime = 'tauri';

export type BuildProfile = 'debug' | 'release';

export type AppearancePreference = 'system' | 'light' | 'dark';

export interface NativeAppInfo {
  readonly name: string;
  readonly version: string;
  readonly buildProfile: BuildProfile;
  readonly runtime: NativeAppRuntime;
  readonly target: string;
}

export interface AppError {
  readonly code: string;
  readonly message: string;
  readonly recoverable: boolean;
  readonly correlationId?: string;
}

export interface AppSettings {
  readonly schemaVersion: number;
  readonly revision: number;
  readonly appearance: AppearancePreference;
  readonly idleUnloadMinutes: number;
}

export interface UpdateAppSettingsRequest {
  readonly expectedRevision: number;
  readonly appearance?: AppearancePreference;
  readonly idleUnloadMinutes?: number;
}

export interface ResetAppSettingsRequest {
  readonly expectedRevision: number;
}
