// Generated by lattice-core. Do not edit by hand.

export const APP_COMMANDS = {
  getAppInfo: 'get_app_info',
  getAppSettings: 'get_app_settings',
  updateAppSettings: 'update_app_settings',
  resetAppSettings: 'reset_app_settings',
  getModelRuntimeStatus: 'get_model_runtime_status',
  configureModelRuntime: 'configure_model_runtime',
  probeModelRuntime: 'probe_model_runtime',
  startModelRuntime: 'start_model_runtime',
  stopModelRuntime: 'stop_model_runtime',
  cancelModelRuntimeOperation: 'cancel_model_runtime_operation',
  getModelSlotStatus: 'get_model_slot_status',
  loadModel: 'load_model',
  unloadModel: 'unload_model',
  cancelModelOperation: 'cancel_model_operation',
  startChatStream: 'start_chat_stream',
  cancelChatStream: 'cancel_chat_stream',
  listConversations: 'list_conversations',
  getConversation: 'get_conversation',
  deleteConversation: 'delete_conversation',
  listCredentials: 'list_credentials',
  createCredential: 'create_credential',
  replaceCredential: 'replace_credential',
  deleteCredential: 'delete_credential',
  listProviderProfiles: 'list_provider_profiles',
  createProviderProfile: 'create_provider_profile',
  updateProviderProfile: 'update_provider_profile',
  deleteProviderProfile: 'delete_provider_profile',
  bindProviderCredential: 'bind_provider_credential',
  grantProviderConsent: 'grant_provider_consent',
  revokeProviderConsent: 'revoke_provider_consent'
} as const;

export type AppCommand = (typeof APP_COMMANDS)[keyof typeof APP_COMMANDS];

export type NativeAppRuntime = 'tauri';

export type BuildProfile = 'debug' | 'release';

export type AppearancePreference = 'system' | 'light' | 'dark';

export type ModelRuntimeAvailability =
  'missing' | 'unsupported' | 'stopped' | 'running' | 'unreachable' | 'unknown';

export type RuntimeDaemonStatus = 'running' | 'notRunning' | 'unknown';

export type RuntimeServerStatus = 'running' | 'stopped' | 'unreachable' | 'unknown';

export type RuntimeOperationOutcome =
  | 'started'
  | 'alreadyRunning'
  | 'stopped'
  | 'alreadyStopped'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export type ModelOperationOutcome =
  | 'loaded'
  | 'alreadyLoaded'
  | 'unloaded'
  | 'alreadyUnloaded'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export interface NativeAppInfo {
  readonly name: string;
  readonly version: string;
  readonly buildProfile: BuildProfile;
  readonly runtime: NativeAppRuntime;
  readonly target: string;
}

export interface AppError {
  readonly code: string;
  readonly message: string;
  readonly recoverable: boolean;
  readonly correlationId?: string;
}

export interface AppSettings {
  readonly schemaVersion: number;
  readonly revision: number;
  readonly appearance: AppearancePreference;
  readonly idleUnloadMinutes: number;
}

export interface UpdateAppSettingsRequest {
  readonly expectedRevision: number;
  readonly appearance?: AppearancePreference;
  readonly idleUnloadMinutes?: number;
}

export interface ResetAppSettingsRequest {
  readonly expectedRevision: number;
}

export interface RuntimeProbeApproval {
  readonly executableFingerprint: string;
  readonly cliVersion: string;
  readonly checkedAtUnixSeconds: number;
}

export interface RuntimeDaemonObservation {
  readonly status: RuntimeDaemonStatus;
  readonly pid?: number;
  readonly isDaemon?: boolean;
  readonly version?: string;
}

export interface RuntimeServerObservation {
  readonly status: RuntimeServerStatus;
  readonly port?: number;
  readonly endpoint?: string;
}

export interface RuntimeOwnershipOwned {
  readonly state: 'owned';
  readonly daemonPid: number;
  readonly executableFingerprint: string;
  readonly ownedSinceUnixSeconds: number;
}

export interface RuntimeOwnershipAttached {
  readonly state: 'attached';
}

export interface RuntimeOwnershipUnknown {
  readonly state: 'unknown';
}

export type RuntimeOwnership =
  RuntimeOwnershipOwned | RuntimeOwnershipAttached | RuntimeOwnershipUnknown;

export interface ModelRuntimeStatus {
  readonly revision: number;
  readonly executablePath?: string;
  readonly availability: ModelRuntimeAvailability;
  readonly cliVersion?: string;
  readonly approved?: RuntimeProbeApproval;
  readonly daemon: RuntimeDaemonObservation;
  readonly server: RuntimeServerObservation;
  readonly ownership: RuntimeOwnership;
  readonly lastOperation?: RuntimeOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}

export interface ConfigureModelRuntimeRequest {
  readonly expectedRevision: number;
  readonly executablePath: string;
}

export interface ProbeModelRuntimeRequest {
  readonly expectedRevision: number;
}

export interface StartModelRuntimeRequest {
  readonly expectedRevision: number;
}

export interface StopModelRuntimeRequest {
  readonly expectedRevision: number;
}

export type CancelModelRuntimeOperationRequest = Record<string, never>;

export interface ModelDescriptor {
  readonly modelKey: string;
  readonly displayName: string;
  readonly architecture?: string;
  readonly isLlm: boolean;
  readonly sizeBytes?: number;
}

export interface LoadedModelObservation {
  readonly identifier: string;
  readonly modelKey: string;
  readonly architecture?: string;
  readonly sizeBytes?: number;
}

export interface ModelLoadOwnershipOwned {
  readonly state: 'owned';
  readonly identifier: string;
  readonly modelKey: string;
  readonly loadedSinceUnixSeconds: number;
}

export interface ModelLoadOwnershipAttached {
  readonly state: 'attached';
  readonly identifier: string;
  readonly modelKey: string;
}

export interface ModelLoadOwnershipUnknown {
  readonly state: 'unknown';
}

export type ModelLoadOwnership =
  ModelLoadOwnershipOwned | ModelLoadOwnershipAttached | ModelLoadOwnershipUnknown;

export interface ModelSlotStatus {
  readonly revision: number;
  readonly installed: readonly ModelDescriptor[];
  readonly loaded?: LoadedModelObservation;
  readonly ownership: ModelLoadOwnership;
  readonly lastOperation?: ModelOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}

export type GetModelSlotStatusRequest = Record<string, never>;

export interface LoadModelRequest {
  readonly expectedRevision: number;
  readonly modelKey: string;
}

export interface UnloadModelRequest {
  readonly expectedRevision: number;
}

export type CancelModelOperationRequest = Record<string, never>;

export type ChatRole = 'system' | 'user' | 'assistant';

export interface ChatMessage {
  readonly role: ChatRole;
  readonly text: string;
}

export interface ChatRequest {
  readonly modelKey: string;
  readonly messages: readonly ChatMessage[];
}

export interface ChatTargetLocal {
  readonly kind: 'local';
}

export interface ChatTargetRemote {
  readonly kind: 'remote';
  readonly profileId: string;
}

// Which destination one chat request is sent to (0.11); applies to that
// request only.
export type ChatTarget = ChatTargetLocal | ChatTargetRemote;

// Amended by 0.9 (conversation persistence) with conversation identity and
// by 0.11 (remote OpenAI-compatible chat) with the per-request target; the
// ChatRequest above is unchanged.
export interface StartChatStreamRequest {
  readonly conversationId: string | null;
  readonly chat: ChatRequest;
  readonly target: ChatTarget;
}

export interface ChatRunHandle {
  readonly runId: string;
  readonly conversationId: string;
}

export interface CancelChatStreamRequest {
  readonly runId: string;
}

export type ChatFinishReason = 'stop' | 'maxOutputTokens';

export interface ChatStreamEventStarted {
  readonly kind: 'started';
  readonly runId: string;
  readonly modelKey: string;
}

export interface ChatStreamEventDelta {
  readonly kind: 'delta';
  readonly runId: string;
  readonly sequence: number;
  readonly text: string;
}

export interface ChatStreamEventCompleted {
  readonly kind: 'completed';
  readonly runId: string;
  readonly sequence: number;
  readonly finishReason: ChatFinishReason;
}

export interface ChatStreamEventCancelled {
  readonly kind: 'cancelled';
  readonly runId: string;
  readonly sequence: number;
}

export interface ChatStreamEventFailed {
  readonly kind: 'failed';
  readonly runId: string;
  readonly sequence: number;
  readonly error: AppError;
}

export type ChatStreamEvent =
  | ChatStreamEventStarted
  | ChatStreamEventDelta
  | ChatStreamEventCompleted
  | ChatStreamEventCancelled
  | ChatStreamEventFailed;

export type GenerationStatus = 'complete' | 'streaming' | 'cancelled' | 'failed' | 'interrupted';

export interface Message {
  readonly id: string;
  readonly conversationId: string;
  readonly sequence: number;
  readonly role: ChatRole;
  readonly text: string;
  readonly status: GenerationStatus;
  readonly providerKey?: string;
  readonly modelKey?: string;
  readonly errorMessage?: string;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}

export interface Conversation {
  readonly id: string;
  readonly title: string;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}

export interface ConversationSummary {
  readonly id: string;
  readonly title: string;
  readonly updatedAtUnixSeconds: number;
  readonly messageCount: number;
  readonly lastStatus?: GenerationStatus;
}

export interface ConversationCursor {
  readonly updatedAtUnixSeconds: number;
  readonly id: string;
}

export interface ListConversationsRequest {
  readonly limit?: number;
  readonly before?: ConversationCursor;
}

export interface ListConversationsResponse {
  readonly conversations: readonly ConversationSummary[];
  readonly nextBefore?: ConversationCursor;
}

export interface GetConversationRequest {
  readonly conversationId: string;
  readonly limit?: number;
  readonly beforeSequence?: number;
}

export interface ConversationDetail {
  readonly conversation: Conversation;
  readonly messages: readonly Message[];
  readonly hasMoreBefore: boolean;
}

export interface DeleteConversationRequest {
  readonly conversationId: string;
}

export type CredentialAvailability = 'available' | 'locked' | 'missing' | 'unsupported';

// No secret field, structurally — Angular never sees a resolved value, only
// this reference shape. See the credentials spec's "Lattice SHALL Acquire A
// New Or Replacement Secret Through Native Entry Only".
export interface CredentialRef {
  readonly id: string;
  readonly label: string;
  readonly providerKey: string;
  readonly availability: CredentialAvailability;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}

export interface CreateCredentialRequest {
  readonly label: string;
  readonly providerKey: string;
}

export interface ReplaceCredentialRequest {
  readonly id: string;
}

export interface DeleteCredentialRequest {
  readonly id: string;
}

// Provenance keys recorded on assistant messages (`Message.providerKey`).
export const PROVIDER_KEYS = {
  local: 'local-openai-compatible',
  remote: 'remote-openai-compatible'
} as const;

// Consent to send conversation context to exactly this endpoint; only
// present while it equals the profile's current endpoint.
export interface ProviderConsent {
  readonly endpoint: string;
  readonly grantedAtUnixSeconds: number;
}

// A remote OpenAI-compatible provider profile. `credentialId` is a
// reference only; no field ever carries a secret.
export interface ProviderProfile {
  readonly id: string;
  readonly revision: number;
  readonly label: string;
  readonly endpoint: string;
  readonly modelKey: string;
  readonly credentialId?: string;
  readonly consent?: ProviderConsent;
  readonly createdAtUnixSeconds: number;
  readonly updatedAtUnixSeconds: number;
}

export interface CreateProviderProfileRequest {
  readonly label: string;
  readonly endpoint: string;
  readonly modelKey: string;
  readonly credentialId: string | null;
}

// Carries no credential: changing the endpoint clears the credential binding
// and consent, which must then be given again explicitly.
export interface UpdateProviderProfileRequest {
  readonly id: string;
  readonly expectedRevision: number;
  readonly label: string;
  readonly endpoint: string;
  readonly modelKey: string;
}

export interface DeleteProviderProfileRequest {
  readonly id: string;
}

export interface BindProviderCredentialRequest {
  readonly id: string;
  readonly expectedRevision: number;
  readonly credentialId: string | null;
}

export interface GrantProviderConsentRequest {
  readonly id: string;
  readonly expectedRevision: number;
  readonly endpoint: string;
}

export interface RevokeProviderConsentRequest {
  readonly id: string;
  readonly expectedRevision: number;
}
