// Generated by lattice-core. Do not edit by hand.

export const APP_COMMANDS = {
  getAppInfo: 'get_app_info',
  getAppSettings: 'get_app_settings',
  updateAppSettings: 'update_app_settings',
  resetAppSettings: 'reset_app_settings',
  getModelRuntimeStatus: 'get_model_runtime_status',
  configureModelRuntime: 'configure_model_runtime',
  probeModelRuntime: 'probe_model_runtime',
  startModelRuntime: 'start_model_runtime',
  stopModelRuntime: 'stop_model_runtime',
  cancelModelRuntimeOperation: 'cancel_model_runtime_operation',
  getModelSlotStatus: 'get_model_slot_status',
  loadModel: 'load_model',
  unloadModel: 'unload_model',
  cancelModelOperation: 'cancel_model_operation',
  startChatStream: 'start_chat_stream',
  cancelChatStream: 'cancel_chat_stream'
} as const;

export type AppCommand = (typeof APP_COMMANDS)[keyof typeof APP_COMMANDS];

export type NativeAppRuntime = 'tauri';

export type BuildProfile = 'debug' | 'release';

export type AppearancePreference = 'system' | 'light' | 'dark';

export type ModelRuntimeAvailability =
  'missing' | 'unsupported' | 'stopped' | 'running' | 'unreachable' | 'unknown';

export type RuntimeDaemonStatus = 'running' | 'notRunning' | 'unknown';

export type RuntimeServerStatus = 'running' | 'stopped' | 'unreachable' | 'unknown';

export type RuntimeOperationOutcome =
  | 'started'
  | 'alreadyRunning'
  | 'stopped'
  | 'alreadyStopped'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export type ModelOperationOutcome =
  | 'loaded'
  | 'alreadyLoaded'
  | 'unloaded'
  | 'alreadyUnloaded'
  | 'refused'
  | 'cancelled'
  | 'timedOut'
  | 'failed';

export interface NativeAppInfo {
  readonly name: string;
  readonly version: string;
  readonly buildProfile: BuildProfile;
  readonly runtime: NativeAppRuntime;
  readonly target: string;
}

export interface AppError {
  readonly code: string;
  readonly message: string;
  readonly recoverable: boolean;
  readonly correlationId?: string;
}

export interface AppSettings {
  readonly schemaVersion: number;
  readonly revision: number;
  readonly appearance: AppearancePreference;
  readonly idleUnloadMinutes: number;
}

export interface UpdateAppSettingsRequest {
  readonly expectedRevision: number;
  readonly appearance?: AppearancePreference;
  readonly idleUnloadMinutes?: number;
}

export interface ResetAppSettingsRequest {
  readonly expectedRevision: number;
}

export interface RuntimeProbeApproval {
  readonly executableFingerprint: string;
  readonly cliVersion: string;
  readonly checkedAtUnixSeconds: number;
}

export interface RuntimeDaemonObservation {
  readonly status: RuntimeDaemonStatus;
  readonly pid?: number;
  readonly isDaemon?: boolean;
  readonly version?: string;
}

export interface RuntimeServerObservation {
  readonly status: RuntimeServerStatus;
  readonly port?: number;
  readonly endpoint?: string;
}

export interface RuntimeOwnershipOwned {
  readonly state: 'owned';
  readonly daemonPid: number;
  readonly executableFingerprint: string;
  readonly ownedSinceUnixSeconds: number;
}

export interface RuntimeOwnershipAttached {
  readonly state: 'attached';
}

export interface RuntimeOwnershipUnknown {
  readonly state: 'unknown';
}

export type RuntimeOwnership =
  RuntimeOwnershipOwned | RuntimeOwnershipAttached | RuntimeOwnershipUnknown;

export interface ModelRuntimeStatus {
  readonly revision: number;
  readonly executablePath?: string;
  readonly availability: ModelRuntimeAvailability;
  readonly cliVersion?: string;
  readonly approved?: RuntimeProbeApproval;
  readonly daemon: RuntimeDaemonObservation;
  readonly server: RuntimeServerObservation;
  readonly ownership: RuntimeOwnership;
  readonly lastOperation?: RuntimeOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}

export interface ConfigureModelRuntimeRequest {
  readonly expectedRevision: number;
  readonly executablePath: string;
}

export interface ProbeModelRuntimeRequest {
  readonly expectedRevision: number;
}

export interface StartModelRuntimeRequest {
  readonly expectedRevision: number;
}

export interface StopModelRuntimeRequest {
  readonly expectedRevision: number;
}

export type CancelModelRuntimeOperationRequest = Record<string, never>;

export interface ModelDescriptor {
  readonly modelKey: string;
  readonly displayName: string;
  readonly architecture?: string;
  readonly isLlm: boolean;
  readonly sizeBytes?: number;
}

export interface LoadedModelObservation {
  readonly identifier: string;
  readonly modelKey: string;
  readonly architecture?: string;
  readonly sizeBytes?: number;
}

export interface ModelLoadOwnershipOwned {
  readonly state: 'owned';
  readonly identifier: string;
  readonly modelKey: string;
  readonly loadedSinceUnixSeconds: number;
}

export interface ModelLoadOwnershipAttached {
  readonly state: 'attached';
  readonly identifier: string;
  readonly modelKey: string;
}

export interface ModelLoadOwnershipUnknown {
  readonly state: 'unknown';
}

export type ModelLoadOwnership =
  ModelLoadOwnershipOwned | ModelLoadOwnershipAttached | ModelLoadOwnershipUnknown;

export interface ModelSlotStatus {
  readonly revision: number;
  readonly installed: readonly ModelDescriptor[];
  readonly loaded?: LoadedModelObservation;
  readonly ownership: ModelLoadOwnership;
  readonly lastOperation?: ModelOperationOutcome;
  readonly lastCheckedUnixSeconds?: number;
  readonly message: string;
}

export type GetModelSlotStatusRequest = Record<string, never>;

export interface LoadModelRequest {
  readonly expectedRevision: number;
  readonly modelKey: string;
}

export interface UnloadModelRequest {
  readonly expectedRevision: number;
}

export type CancelModelOperationRequest = Record<string, never>;

export type ChatRole = 'system' | 'user' | 'assistant';

export interface ChatMessage {
  readonly role: ChatRole;
  readonly text: string;
}

export interface ChatRequest {
  readonly modelKey: string;
  readonly messages: readonly ChatMessage[];
}

export interface ChatRunHandle {
  readonly runId: string;
}

export interface CancelChatStreamRequest {
  readonly runId: string;
}

export type ChatFinishReason = 'stop' | 'maxOutputTokens';

export interface ChatStreamEventStarted {
  readonly kind: 'started';
  readonly runId: string;
  readonly modelKey: string;
}

export interface ChatStreamEventDelta {
  readonly kind: 'delta';
  readonly runId: string;
  readonly sequence: number;
  readonly text: string;
}

export interface ChatStreamEventCompleted {
  readonly kind: 'completed';
  readonly runId: string;
  readonly sequence: number;
  readonly finishReason: ChatFinishReason;
}

export interface ChatStreamEventCancelled {
  readonly kind: 'cancelled';
  readonly runId: string;
  readonly sequence: number;
}

export interface ChatStreamEventFailed {
  readonly kind: 'failed';
  readonly runId: string;
  readonly sequence: number;
  readonly error: AppError;
}

export type ChatStreamEvent =
  | ChatStreamEventStarted
  | ChatStreamEventDelta
  | ChatStreamEventCompleted
  | ChatStreamEventCancelled
  | ChatStreamEventFailed;
